const { generateAnalysis } = require("../services/aiService");
const { getRealTrends } = require("../services/data");

const getTrends = async (req, res) => {
  try {
    // 🔥 DATA RÉELLE
    let trends = await getRealTrends();

    // 🔥 1. score
    trends = trends.map(trend => ({
      ...trend,
      score: trend.popularity + trend.growth
    }));

    // 🔥 2. tri
    trends.sort((a, b) => b.score - a.score);

    // 🔥 3. IA
    for (let trend of trends) {
      const aiResponse = await generateAnalysis(trend);

      trend.analysis = aiResponse;
      trend.idea = "Generated by AI";
    }

    res.status(200).json(trends);

  } catch (error) {
    console.error("Trend error:", error.message);
    res.status(500).json({ message: error.message });
  }
};

module.exports = { getTrends };